authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.user_register, name='user_register'),
    path('user/profile/', authapp.user_profile, name='user_profile'),
]

basketapp/urls.py
from django.urls import path, re_path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    re_path(r'^add/product/(?P<pk>\d+)/$', basketapp.add, name='add'),
    re_path(r'^delete/basket/position/(?P<pk>\d+)/$', basketapp.delete, name='delete'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('app/admin/', include('adminapp.urls', namespace='admin_app')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basketapp/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
from django.db.models import Sum

from mainapp.models import Product


class BasketPosition(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    add_datatime = models.DateTimeField(auto_now_add=True)

basketapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse

# Create your views here.
from django.template import loader
from django.template.loader import render_to_string
from django.urls import reverse

from basketapp.models import BasketPosition
from mainapp.models import Product


@login_required
def index(request):
    basket_positions = request.user.basketposition_set.all()
    context = {
        'title_page': 'корзина',
        'basket_positions': basket_positions,
    }

    return render(request, 'basketapp/index.html', context)


@login_required
def add(request, pk):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(
            reverse(
                'main:page_product',
                kwargs={'pk': pk}
            )
        )
    product = get_object_or_404(Product, pk=pk)
    basket = request.user.basketposition_set.filter(product=pk).first()

    if not basket:
        basket = BasketPosition(user=request.user, product=product)

    basket.quantity += 1
    basket.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def delete(request, pk):
    get_object_or_404(BasketPosition, pk=pk).delete()
    return HttpResponseRedirect(reverse('basket:index'))


@login_required
def basket_edit(request, pk, quantity):
    if request.is_ajax():
        quanty = int(quantity)
        new_basket_item = BasketPosition.objects.filter(pk=int(pk)).first()

        if quanty > 0:
            new_basket_item.quantity = quanty
            new_basket_item.save()
        else:
            new_basket_item.delete()

        basket_positions = BasketPosition.objects.filter(user=request.user)

        context = {
            'basket_positions': basket_positions,
        }

        result = loader.render_to_string(
            'basketapp/includes/inc__basket_items.html',
            context=context,
            request=request,
        )

        return JsonResponse({
            'result': result,
        })

basketapp/templates/basketapp/includes/inc__basket_items.html
{% load static %}
{% load mytegs %}

<div class="b_list">
    <div class="basket_record">
        <span class="img_bask">Фото</span>
        <span class="categoryprod">Категория</span>
        <span class="prodname">Продукт</span>
        <span class="prodprice">цена</span>
        <span class="colprod">количество</span>
    </div>
    <hr>
    {% for position in basket_positions %}
    <div class="basket_record">
        <img class="img_bask" src="/media/{{ position.product.image }}" alt="{{ position.product.short_descr }}">
        <span class="categoryprod">{{ position.product.category.name }}</span>
        <span class="prodname">{{ position.product.name }}</span>
        <span class="prodprice">{{ position.product.price }}</span>
        <input type="number" name="{{ position.pk }}" min="0" max="position.product.quantity" value="{{ position.quantity }}" class="colprod">
        <div class="basket">
            <a href="{% url 'basket:delete' position.pk %}" class="dela linkli">
                удалить
            </a>
        </div>
    </div>
    {% endfor %}

    <div class="total">
        <p>
            Количество товаров в корзине: {{ user.col_prod }} шт.
        </p>
        <p>
            На сумму: {{ user.cost_prod }} руб. <br>
            сумма со скидкой: {{ user.cost_prod|sale5 }} руб.
        </p>
    </div>
</div>