authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.user_register, name='user_register'),
    path('user/profile/', authapp.user_profile, name='user_profile'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('app/admin/', include('adminapp.urls', namespace='admin_app')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('catalog/', mainapp.catalog, name='catalog'),
    re_path(r'^products/category/(?P<pk>\d+)/$', mainapp.prodcat, name='products'),
    re_path(r'^products/category/(?P<pk>\d+)/page/(?P<page>\d+)$', mainapp.prodcat, name='products_page'),
    re_path(r'^product/(?P<pk>\d+)$', mainapp.page_product, name='page_product'),
    path('contact/', mainapp.contact, name='contact'),
]

authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.


class ShopUser(AbstractUser):
    userphoto = models.ImageField(name='photo', upload_to='user_photo', default='user_photo/logo.png')
    ageuser = models.SmallIntegerField(verbose_name='возраст', name='age', blank=True, default=0)

    def col_prod(self):
        return sum(position.quantity for position in self.basketposition_set.all())

    def cost_prod(self):
        return sum(position.product.price * position.quantity for position in self.basketposition_set.all())

authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm, UserChangeForm


from authapp.models import ShopUser

from django.utils.translation import gettext_lazy as _


class ShopAuthenticationForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'forminput {field_name}'
            field.widget.attrs['placeholder'] = field_name


class ShopRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'password1', 'password2', 'photo', 'age')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'forminputreg {field_name}'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Регистрация c 18 лет")
        return data


class ShopUserProfileForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'age', 'photo')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'forminput {field_name}'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Регистрация c 18 лет")
        return data

authapp/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from authapp.forms import ShopAuthenticationForm, ShopRegisterForm, ShopUserProfileForm


def login(request):
    form = None
    redirect_url = request.GET.get('next', None)

    if request.method == "POST":
        form = ShopAuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                redirect_url = request.POST.get('redirect_url', None)
                auth.login(request, user)
                if redirect_url:
                    return HttpResponseRedirect(redirect_url)
                return HttpResponseRedirect(reverse('main:index'))
    elif request.method == "GET":
        form = ShopAuthenticationForm()

    context = {
        'title_page': 'аутентификация',
        'form': form,
        'redirect_url': redirect_url,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def user_register(request):
    register_form = None
    if request.method == 'POST':
        register_form = ShopRegisterForm(request.POST, request.FILES)
        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    elif request.method == 'GET':
        register_form = ShopRegisterForm()

    context = {
        'title_page': 'регистрация',
        'register_form': register_form
    }
    return render(request, 'authapp/user_register.html', context)


def user_profile(request):
    form = ShopUserProfileForm()

    if request.method == 'POST':
        form = ShopUserProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:user_profile'))
    else:
        form = ShopUserProfileForm(instance=request.user)

    context = {
        'title_page': 'Профиль',
        'form': form
    }
    return render(request, 'authapp/user_profile.html', context)

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="UTF-8">
    <title>
        {{ title_page|default:"главная"|title }}
    </title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/log1.css' %}">
    {% endblock %}
</head>

<body>
    <div class="conter">
        <div class="login">
            <div class="logod"><a href="{% url 'main:index' %}"><img class="logo" src="{% static 'img/logo.png' %}" alt="logo"></a></div>
            {% block content %}

            {% endblock %}
            <div class="adiv">
                <a href="{% url 'mainapp:index' %}"
                   class="alogin">
                    на главную
                </a>
            </div>
        </div>

        <div class="cln"></div>

    </div>
</body>

</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% block content%}
<div class="h2center">
    Вход в систему
</div>
<form class="formlogin" method="post">
    {% csrf_token %}
    {% if redirect_url %}
        <input type="hidden" name="redirect_url" value="{{ redirect_url }}">
    {% endif %}
    {{ form.as_p }}
    <button class="logbut">войти</button>
</form>
<div class="adiv">
    <a href="{% url 'auth:user_register' %}"
       class="alogin">
        зарегистрироваться
    </a>
</div>
{% endblock %}

authapp/templates/authapp/user_profile.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block content%}
<div class="h2center">
    Профиль
</div>
<div class="user_photo1 clearfix">
    <img src="/media/{{ user.photo }}" class="imguser">
</div>
<form class="formprofil" action="{% url 'auth:user_profile' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="logbut">Сохранить</button>
</form>
{% endblock %}

authapp/templates/authapp/user_register.html
{% extends 'authapp/base.html' %}
{% block content%}
<div class="h2center">
    Регистрация
</div>
<form class="formlogin" action="{% url 'auth:user_register' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ register_form.as_p }}
    <button class="regbut">Зарегистрироваться</button>
</form>

{% endblock %}