adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.UserList.as_view(), name='index'),
    path('user/create/', adminapp.user_create, name='user_create'),
    path('user/<int:pk>/update/', adminapp.user_update, name='user_update'),
    path('user/<int:pk>/delete/', adminapp.user_delete, name='user_delete'),
    path('user/<int:pk>/recover/', adminapp.user_recover, name='user_recover'),
    path('categories/', adminapp.ProductCategoriesList.as_view(), name='categories'),
    path('categories/category/create/', adminapp.ProductCategoryCreate.as_view(), name='category_create'),
    path('categories/category/<int:pk>/update/', adminapp.ProductCategoryUpdate.as_view(), name='category_update'),
    path('categories/category/<int:pk>/delete/', adminapp.ProductCategoryDelete.as_view(), name='category_delete'),
    path('categories/category/<int:pk>/recover/', adminapp.category_recover, name='category_recover'),
    # path('categories/product/', adminapp.ProductList.as_view(), name='product'),
    # path('categories/product/create/', adminapp.ProductCreate.as_view(), name='product_create'),
    path('categories/<int:category_pk>/product/create/', adminapp.product_create, name='product_create'),
    path('categories/product/<int:category_pk>/', adminapp.products_in_category, name='products_in_category'),
    path('categories/product/<int:pk>/update/', adminapp.ProductUpdate.as_view(), name='product_update'),
    path('categories/product/<int:pk>/delete/', adminapp.ProductDelete.as_view(), name='product_delete'),
    path('categories/product/<int:pk>/recover/', adminapp.product_recover, name='product_recover'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.user_register, name='user_register'),
    path('user/profile/', authapp.user_profile, name='user_profile'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('app/admin/', include('adminapp.urls', namespace='admin_app')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from authapp.forms import forms
from authapp.models import ShopUser
from mainapp.models import CategoryProduct, Product


class AdminShopUserCreateForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            'username', 'first_name', 'last_name', 'is_superuser',
            'is_staff', 'email', 'password1', 'password2', 'photo',
            'age',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'forminputreg {field_name}'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Регистрация c 18 лет")
        return data


class AdminShopUserUpdateForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            'username', 'first_name', 'last_name', 'is_superuser',
            'is_staff', 'is_active', 'email', 'password', 'photo',
            'age',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'forminputreg {field_name}'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Регистрация c 18 лет")
        return data


class AdminProductCategoryCreateForm(forms.ModelForm):
    class Meta:
        model = CategoryProduct
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'forminputreg1 {field_name}'


class AdminProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'forminputreg1 {field_name}'

adminapp/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from adminapp.forms import AdminShopUserCreateForm, AdminShopUserUpdateForm, AdminProductCategoryCreateForm, \
    AdminProductCreateForm
from mainapp.models import CategoryProduct, Product


# @user_passes_test(lambda x: x.is_superuser)
# def index(request):
#     users_list = get_user_model().objects.all().order_by(
#         '-is_active', '-is_superuser', '-is_staff', 'username'
#     )
#
#     context = {
#         'page_title': 'администрирование/пользователи',
#         'users_list': users_list,
#     }
#     return render(request, 'authapp/shopuser_list.html', context)

class OnlySuperUserMixin:
    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class TitlePageMixin:
    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data(object_list=None, **kwargs)
        data['page_title'] = self.page_title
        return data


class UserList(OnlySuperUserMixin, TitlePageMixin, ListView):
    page_title = 'админка/пользователи'
    model = get_user_model()


@user_passes_test(lambda x: x.is_superuser)
def user_create(request):
    if request.method == 'POST':
        user_form = AdminShopUserCreateForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('adminapp:index'))
    else:
        user_form = AdminShopUserCreateForm()

    context = {
        'page_title': 'пользователь/создание',
        'user_form': user_form,
    }
    return render(request, 'adminapp/user_update.html', context)


class ProductCategoriesList(OnlySuperUserMixin, TitlePageMixin, ListView):
    page_title = 'админка/категории'
    model = CategoryProduct
    # paginate_by = 5


# class ProductList(OnlySuperUserMixin, TitlePageMixin, ListView):
#     page_title = 'админка/продукты'
#     model = Product

@user_passes_test(lambda x: x.is_superuser)
def products_in_category(request, category_pk):
    category = get_object_or_404(CategoryProduct, pk=category_pk)
    object_list = category.product_set.all()
    context = {
        'page_title': f'категория {category.name}/продукты',
        'category': category,
        'object_list': object_list,
    }
    return render(request, 'adminapp/category_products_list.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_update(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    if request.method == 'POST':
        user_form = AdminShopUserUpdateForm(request.POST, request.FILES, instance=user)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('adminapp:index'))
    else:
        user_form = AdminShopUserUpdateForm(instance=user)

    context = {
        'page_title': 'пользователь/редактирование',
        'user_form': user_form,
    }
    return render(request, 'adminapp/user_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_delete(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('adminapp:index'))
    else:
        context = {
            'page_title': 'пользователь/удаление',
            'user_to_delete': user,
        }
        return render(request, 'adminapp/user_delete.html', context)


@user_passes_test(lambda x: x.is_superuser)
def user_recover(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    user.is_active = True
    user.save()
    return HttpResponseRedirect(reverse('adminapp:index'))


class ProductCategoryCreate(OnlySuperUserMixin, TitlePageMixin, CreateView):
    page_title = 'админка/категории/создание'
    model = CategoryProduct
    success_url = reverse_lazy('adminapp:categories')
    # fields = '__all__'
    form_class = AdminProductCategoryCreateForm


class ProductCategoryUpdate(OnlySuperUserMixin, TitlePageMixin, UpdateView):
    page_title = 'админка/категории/редактирование'
    model = CategoryProduct
    success_url = reverse_lazy('adminapp:categories')
    # fields = '__all__'
    form_class = AdminProductCategoryCreateForm


class ProductCategoryDelete(OnlySuperUserMixin, TitlePageMixin, DeleteView):
    page_title = 'админка/категории/удаление'
    model = CategoryProduct
    success_url = reverse_lazy('adminapp:categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda x: x.is_superuser)
def category_recover(request, pk):
    category = get_object_or_404(CategoryProduct, pk=pk)
    category.is_active = True
    category.save()
    return HttpResponseRedirect(reverse('adminapp:categories'))


# class ProductCreate(OnlySuperUserMixin, TitlePageMixin, CreateView):
#     page_title = 'админка/продукт/создание'
#     model = Product
#     success_url = reverse_lazy('adminapp:product')
#     # fields = '__all__'
#     form_class = AdminProductCreateForm

@user_passes_test(lambda u: u.is_superuser)
def product_create(request, category_pk):
    category = get_object_or_404(CategoryProduct, pk=category_pk)
    if request.method == 'POST':
        form = AdminProductCreateForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse(
                'adminapp:products_in_category',
                # 'adminapp:categories',
                kwargs={'category_pk': category.pk}
            ))
    else:
        form = AdminProductCreateForm(
            initial={
                'category': category,
            }
        )

    context = {
        'page_title': 'продукты/создание',
        'form': form,
        'category': category,
    }
    return render(request, 'adminapp/product_update.html', context)


class ProductUpdate(OnlySuperUserMixin, TitlePageMixin, UpdateView):
    page_title = 'админка/продукт/редактирование'
    model = Product
    success_url = reverse_lazy('adminapp:categories')
    # fields = '__all__'
    form_class = AdminProductCreateForm


class ProductDelete(OnlySuperUserMixin, TitlePageMixin, DeleteView):
    page_title = 'админка/продукт/удаление'
    model = Product

    # success_url = reverse_lazy('adminapp:products_in_category', kwargs={'category_pk': get_object().category.pk})

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(
            reverse('adminapp:products_in_category', kwargs={'category_pk': self.object.category.pk}))


@user_passes_test(lambda x: x.is_superuser)
def product_recover(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.is_active = True
    product.save()
    return HttpResponseRedirect(reverse('adminapp:products_in_category', kwargs={'category_pk': product.category.pk}))

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="UTF-8">
    <title>
        {{ page_title|default:"главная"|title }}
    </title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/adminapp1.css' %}">
    <link rel="stylesheet" href="{% static 'css/log1.css' %}">
    {% endblock %}
    {% block js %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    {% endblock %}
</head>

<body>
    <div class="conter">
        {% block menu %}
        <div class="div_h1_basket"><h1>админка</h1></div>

        {% include 'adminapp/includes/inc__menu_admin.html' %}
        {% endblock %}
        {% block content %}

        {% endblock %}
        <div class="cln"></div>
    </div>
    {% block footer %}
    <div class="footer">
        <div class="foot">
            <p class="fp"><b>Наши контакты:</b></p>
            <p class="fp">тел: 8(999) 564 54 12</p>
            <p class="fp">Адрес: г.Москва, ул. Арбат, 54/с2</p>
        </div>
        <div class="foot">
            <p class="fp"><b>Полезное:</b></p>
            <p class="fp"><a href="#" class="foota">Сотрудничать</a></p>
            <p class="fp"><a href="#" class="foota">Написать нам</a></p>
        </div>
        <div class="date">Сегодня: <b>{% now "d.m.Y" %}</b></div>
    </div>
    {% endblock %}
</body>

</html>

adminapp/templates/adminapp/category_products_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="basket_list">

{% if object_list %}
<div class="div_h1_basket1">продукты в категории {{ category.name }}</div>
<div class="b_list">
    <div class="butadmin">
            <a href="{% url 'adminapp:product_create' category_pk=category.pk %}" class="dela linkli">
                создать
            </a>
        </div>
    <div class="basket_record">
        <span class="categoryprod">Название</span>
        <span class="categoryprod">Описание</span>
        <span class="categoryprod">Активность</span>
    </div>
    <hr>
    {% for position in object_list %}
    <div class="basket_record {% if not position.is_active %} notaction {% endif %}">
        <span class="categoryprod">{{ position.name }}</span>
        <span class="categoryprod">{{ position.description }}</span>
        <span class="categoryprod">{{ position.is_active }}</span>
        <div class="butadmin">
            {% if position.is_active %}
            <a href="{% url 'adminapp:product_delete' pk=position.pk %}" class="dela linkli">
                удалить
            </a>
            {% else %}
            <a href="{% url 'adminapp:product_recover' pk=position.pk %}" class="dela linkli">
                восстановить
            </a>
            {% endif %}
        </div>
        <div class="butadmin">
            <a href="{% url 'adminapp:product_update' pk=position.pk %}" class="dela linkli">
                редактировать
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
пока пусто!
{% endif %}
</div>
<div class="adiv">
    <a href="{% url 'adminapp:categories' %}"
       class="alogin">
        вернуться
    </a>
</div>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% block menu %}

{% endblock %}
{% block content%}
<div class="h2centeradmin clearfix">
    Продукт:
</div>
<form class="formcateg" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="regbut1">сохранить</button>
</form>
<div class="adiv">
    <a href="{% url 'adminapp:products_in_category' category_pk=category.pk %}"
       class="alogin">
        вернуться
    </a>
</div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% block menu %}

{% endblock %}
{% block content%}
<div class="winsave">
<div class="h2centeradmin clearfix">
    заблокировать пользователя {{ user_to_delete.username }}?
</div>
<form class="formlogin" method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить" class="inpdel formmarg">
</form>
<ul class="inpdel">
   <li class="ullimenuadm">
        <a href="{% url 'adminapp:index' %}" class="linkliadm">
            отмена
        </a>
   </li>
</ul>
</div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% block menu %}

{% endblock %}
{% block content%}
<div class="h2centeradmin clearfix">
    пользователь:
</div>
<form class="formlogin" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    <button class="regbut">сохранить</button>
</form>
<div class="adiv">
    <a href="{% url 'adminapp:index' %}"
       class="alogin">
        вернуться
    </a>
</div>
{% endblock %}