adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.UserList.as_view(), name='index'),
    path('user/create/', adminapp.user_create, name='user_create'),
    path('user/<int:pk>/update/', adminapp.user_update, name='user_update'),
    path('user/<int:pk>/delete/', adminapp.user_delete, name='user_delete'),
    path('user/<int:pk>/recover/', adminapp.user_recover, name='user_recover'),
    path('categories/', adminapp.ProductCategoriesList.as_view(), name='categories'),
    path('categories/category/create/', adminapp.ProductCategoryCreate.as_view(), name='category_create'),
    path('categories/category/<int:pk>/update/', adminapp.ProductCategoryUpdate.as_view(), name='category_update'),
    path('categories/category/<int:pk>/delete/', adminapp.ProductCategoryDelete.as_view(), name='category_delete'),
    path('categories/category/<int:pk>/recover/', adminapp.category_recover, name='category_recover'),
    # path('categories/product/', adminapp.ProductList.as_view(), name='product'),
    # path('categories/product/create/', adminapp.ProductCreate.as_view(), name='product_create'),
    path('categories/<int:category_pk>/product/create/', adminapp.product_create, name='product_create'),
    path('categories/product/<int:category_pk>/', adminapp.products_in_category, name='products_in_category'),
    path('categories/product/<int:pk>/update/', adminapp.ProductUpdate.as_view(), name='product_update'),
    path('categories/product/<int:pk>/delete/', adminapp.ProductDelete.as_view(), name='product_delete'),
    path('categories/product/<int:pk>/recover/', adminapp.product_recover, name='product_recover'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.user_register, name='user_register'),
    path('user/profile/', authapp.user_profile, name='user_profile'),
]

basketapp/urls.py
from django.urls import path, re_path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    re_path(r'^add/product/(?P<pk>\d+)/$', basketapp.add, name='add'),
    re_path(r'^delete/basket/position/(?P<pk>\d+)/$', basketapp.delete, name='delete'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('app/admin/', include('adminapp.urls', namespace='admin_app')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('catalog/', mainapp.catalog, name='catalog'),
    re_path(r'^products/category/(?P<pk>\d+)/$', mainapp.prodcat, name='products'),
    re_path(r'^products/category/(?P<pk>\d+)/page/(?P<page>\d+)$', mainapp.prodcat, name='products_page'),
    re_path(r'^product/(?P<pk>\d+)$', mainapp.page_product, name='page_product'),
    path('contact/', mainapp.contact, name='contact'),
]

mainapp/models.py
from django.db import models


# Create your models here.

class CategoryProduct(models.Model):
    name = models.CharField(verbose_name='наименование категории', max_length=128, unique=True)
    description = models.TextField(verbose_name='описание категории', blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.__class__.__name__}: {self.name}'


class Product(models.Model):
    category = models.ForeignKey(verbose_name='категория товара', to=CategoryProduct, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='наименование', max_length=128)
    image = models.ImageField(upload_to='prodacts_photo', blank=True, default='prodacts_photo/logo.png')
    short_descr = models.CharField(verbose_name='краткое описание товара', max_length=64, blank=True)
    description = models.TextField(verbose_name='описание товара', blank=True)
    price = models.DecimalField(verbose_name='Цена', max_digits=12, decimal_places=2, default=0)
    quantity = models.IntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

mainapp/views.py
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Sum
from django.shortcuts import render, get_object_or_404
import json

# Create your views here.
from basketapp.models import BasketPosition
from mainapp.models import CategoryProduct, Product

with open('mainapp/jsonapp/links_main_menu.json', encoding="UTF-8") as links_main_menu_json:
    links_main_menu = json.load(links_main_menu_json)

products = Product.objects.all()


def get_menu():
    return CategoryProduct.objects.all()


def get_hot_product():
    products_hot = Product.objects.all()
    return random.choice(products_hot)


def related_prods(product):
    return Product.objects.filter(category=product.category).exclude(id=product.id)[:3]


def index(request):
    context = {
        'title_page': 'главная',
        'links_main_menu': links_main_menu,
        'categories': get_menu(),
    }
    return render(request, 'mainapp/index.html', context)


def catalog(request):
    hot_product = get_hot_product()
    related_products = related_prods(hot_product)

    context = {
        'title_page': 'каталог',
        'links_main_menu': links_main_menu,
        'categories': get_menu(),
        'products': products,
        'hot_product': hot_product,
        'related_products': related_products,
    }
    return render(request, 'mainapp/catalog.html', context)


def page_product(request, pk):
    related_products = related_prods(get_object_or_404(Product, pk=pk))
    context = {
        'title_page': 'каталог',
        'links_main_menu': links_main_menu,
        'categories': get_menu(),
        'products': products,
        'product': get_object_or_404(Product, pk=pk),
        'related_products': related_products,
    }
    return render(request, 'mainapp/page_product.html', context)


def contact(request):
    locations = [
        {
            'city': 'Москва',
            'position': 'ул. Удальцова, д. 18',
            'phone': '8 (495) 565 56 78',
        },
        {
            'city': 'Москва',
            'position': 'ул. Арбат, д. 24/С2',
            'phone': '8 (495) 577 66 23',
        },
        {
            'city': 'В.Новгород',
            'position': 'ул. Московская, д. 23',
            'phone': '8 (8212) 56 56 21',
        },
        {
            'city': 'Санкт-Петербург',
            'position': 'ул. Оптиков, д. 13',
            'phone': '8 (812) 556 00 99',
        },
    ]
    context = {
        'title_page': 'контакты',
        'locations': locations,
        'links_main_menu': links_main_menu,
    }
    return render(request, 'mainapp/contact.html', context)


def prodcat(request, pk, page=1):
    if int(pk) == 0:
        category = {'pk': 0, 'name': 'все'}
        prods = Product.objects.all()
    else:
        category = get_object_or_404(CategoryProduct, pk=pk)
        prods = Product.objects.filter(category=category)

    product_paginator = Paginator(prods, 2)
    try:
        prods = product_paginator.page(page)
    except PageNotAnInteger:
        prods = product_paginator.page(1)
    except EmptyPage:
        prods = product_paginator.page(product_paginator.num_pages)

    context = {
        'title_page': 'каталог',
        'links_main_menu': links_main_menu,
        'categories': get_menu(),
        'category': category,
        'prods': prods,
    }
    return render(request, 'mainapp/prodcat.html', context)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="UTF-8">
    <title>
        {{ title_page|default:"главная"|title }}
    </title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
</head>

<body>
    <div class="conter">
        <div class="slider clearfix" id="img1">
            <div class="clearfix">
                <div class="logod"><a href="{% url 'main:index' %}"><img class="logo" src="{% static 'img/logo.png' %}" alt="logo"></a></div>
                <div class="menu">
                    <ul class="ulmenu">
                       {% for link in links_main_menu %}
                        <li class="ullimenu">
                            <a href="{% url link.href %}" class="linkli {% if request.resolver_match.url_name == link.url_name or request.resolver_match.url_name == 'products' and link.url_name == 'catalog' %} menuactive {% endif %}">
                                {{ link.name }}
                            </a>
                        </li>
                        {% endfor %}
                        {% if user.is_authenticated %}
                        <li class="ullimenu">
                            <a href="{% url 'auth:user_profile' %}" class="linkli">
                                {{ user.first_name|default:'Пользователь' }}
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                    <ul class="ulmenu">
                       <li class="ullimenu">
                            {% if user.is_authenticated %}
                                <a href="{% url 'auth:logout' %}" class="linkli">
                                    выйти
                                </a>
                            {% else %}
                                <a href="{% url 'auth:login' %}" class="linkli">
                                    войти
                                </a>
                            {% endif %}
                       </li>
                    </ul>
                    {% if user.is_authenticated %}
                    <div class="basket">
                        <a href="{% url 'basket:index' %}" class="basketa linkli">
                            Корзина
                            <img src="{% static 'img/basket.png' %}" class="basketimg" alt="Корзина">
                            {{ user.col_prod }}шт({{ user.cost_prod|floatformat:0 }}руб)
                        </a>
                    </div>
                    {% endif %}
                    {% if user.is_superuser %}
                    <ul class="ulmenuadmin">
                    <li class="ullimenu">
                            <a href="{% url 'adminapp:index' %}" class="linkli">
                                админка
                            </a>
                    </li>
                    </ul>
                    {% endif %}
                </div>
            </div>
            <button class="left">&lt;</button>
            <button class="right">&gt;</button>
        </div>
        {% block content %}

        {% endblock %}
        <div class="cln"></div>
    </div>
    {% block footer %}
    <div class="footer">
        <div class="foot">
            <p class="fp"><b>Наши контакты:</b></p>
            <p class="fp">тел: 8(999) 564 54 12</p>
            <p class="fp">Адрес: г.Москва, ул. Арбат, 54/с2</p>
        </div>
        <div class="foot">
            <p class="fp"><b>Полезное:</b></p>
            <p class="fp"><a href="#" class="foota">Сотрудничать</a></p>
            <p class="fp"><a href="#" class="foota">Написать нам</a></p>
        </div>
        <div class="date">Сегодня: <b>{% now "d.m.Y" %}</b></div>
    </div>
    {% endblock %}
    <script src="{% static 'js/scr.js' %}"></script>
</body>

</html>

mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
{% include 'mainapp/includes/inc__catalog_menu.html' %}
<div class="prodact clearfix">
    <h1>Успей купить</h1>
    <div class="prod">
        <a href="{% url 'main:page_product' pk=hot_product.pk %}"><img src="/media/{{ hot_product.image }}" class="imgprod" alt="Фото"></a>
        <p class="pr">{{ hot_product.name }}</p>
        <p class="pr">{{ hot_product.short_descr }}</p>
        <p class="pr">Цена, в руб:</p>
        <p class="pr prise">{{ hot_product.price }}</p>
        <div class="basket"><a href="{% url 'basket:add' pk=hot_product.pk %}" class="basketa linkli">Купить</a></div>
    </div>
</div>
<div class="prodact clearfix">
    <h1>похожие товары</h1>
    {% for product in related_products %}
    {% include 'mainapp/includes/inc__product_in_list.html' %}
    {% endfor %}
</div>
<div class="prodact clearfix">
    <h1>каталог</h1>
    {% for product in products %}
    <div class="prod">
        <a href="{% url 'main:page_product' pk=product.pk %}"><img src="/media/{{ product.image }}" class="imgprod" alt="Фото"></a>
        <p class="pr">{{ product.name }}</p>
        <p class="pr">{{ product.short_descr }}</p>
        <p class="pr">Цена, в руб:</p>
        <p class="pr prise">{{ product.price }}</p>
        <div class="basket"><a href="{% url 'basket:add' pk=product.pk %}" class="basketa linkli">Купить</a></div>
    </div>
    {% endfor %}
</div>

{% endblock %}

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
<div class="cont">
  {% if locations %}
   {% for location in locations %}
    <div class="contact">
        <p class="con">г. {{ location.city }}</p>
        <p class="con">{{ location.position }}</p>
        <p class="con">тел.: {{ location.phone }}</p>
        <p class="con"><img src="{% static 'img/logo.png' %}" alt="Магазин" class="contimg"></p>
    </div>
    {% endfor %}
    {% else %}
    <h3>Данные скоро будут загружены</h3>
    {% endif %}
    
</div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

        {% include 'mainapp/includes/inc__catalog_menu.html' %}

{% endblock %}

mainapp/templates/mainapp/page_product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="prodact_page clearfix">
    <div class="prod_page">
        <img src="/media/{{ product.image }}" class="imgprod_page" alt="Фото">
        <div class="pr_page_text">
            <p class="pr_page_name">{{ product.name }}</p>
            <p class="pr_page">{{ product.description }}</p>
            <p class="pr_page prise">{{ product.price }} руб.</p>
            <div class="basket_page"><a href="{% url 'basket:add' pk=product.pk %}" class="basketa_page linkli">Купить</a></div>
        </div>
    </div>
</div>
<div class="prodact clearfix">
    <p>похожие товары</p>
    {% for product in related_products %}
    {% include 'mainapp/includes/inc__product_in_list.html' %}
    {% endfor %}
</div>

{% endblock %}

mainapp/templates/mainapp/prodcat.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
{% include 'mainapp/includes/inc__catalog_menu.html' %}
<div class="prodact clearfix">
    <h2>продукты в категории {{ category.name|capfirst }}</h2>
    <div class="paginator">
        {% if prods.has_previous %}
            <a href="{% url 'main:products_page' pk=category.pk page=prods.previous_page_number %}">
                <
            </a>
        {% endif %}
        <span class="current">страница {{ prods.number }} из {{ prods.paginator.num_pages }}</span>
        {% if prods.has_next %}
            <a href="{% url 'main:products_page' pk=category.pk page=prods.next_page_number %}">
                >
            </a>
        {% endif %}
    </div>
    {% for product in prods %}
        <div class="prod">
            <a href="{% url 'main:page_product' pk=product.pk %}"><img src="/media/{{ product.image }}" class="imgprod" alt="Фото"></a>
            <p class="pr">{{ product.name }}</p>
            <p class="pr">{{ product.short_descr }}</p>
            <p class="pr">Цена, в руб:</p>
            <p class="pr prise">{{ product.price }}</p>
            <div class="basket"><a href="{% url 'basket:add' pk=product.pk %}" class="basketa linkli">Купить</a></div>
        </div>
    {% endfor %}
</div>
{% endblock %}